### PR TITLE
Fix build with srcdir != builddir

### PR DESCRIPTION
**Pull request by hadess**

### CODE REVIEW

**Comment by hadess** [comment]
`srcdir != builddir` is the default for `jhbuild`.

**Comment by hadess** [comment]
Rebased as it's still relevant.

**Comment by tihmstar** [comment]
i don't think this is still relevant, is it?

**Comment by hadess** [comment]
> i don't think this is still relevant, is it?

Was eventually fixed by commit 45e6f58678bb7682b29f545fde907a35de8cd2e3

**Pull request closed without merging**
